### ISSUE TITLE
Release user instellen

### ISSUE THREAD

**Issue by Michel-Verhoeven** [GemeenteNijmegen/design-system#24]
publish to npm job faalt nog omdat deze moet gebeuren vanuit een token met [de permission om de branch protection te bypassen](https://github.blog/changelog/2022-08-18-bypass-branch-protections-with-a-new-permission/)

- [x] User / token met de goede rechten aanmaken
- [x] [Benodigde secrets](https://github.com/GemeenteNijmegen/design-system/blob/964c2c45a1d6d79b0a677f7c1980798aa3b8c478/.github/workflows/continuous-deployment.yml#L189-L200) instellen op de repo

**Comment by joostvanderborg** [comment]
@MartijnvDijk Een role aanmaken die branch protection bypass heeft moet in de Github organisation. Kun jij dit instellen? Evt. even overleggen met Michel of het allemaal werkt, er zijn toch elke keer meer stappen nodig dan ik dacht ;). De GH_TOKEN bevat nu de 'standaard'-token, er zal een nieuwe ingericht moeten worden met die role gok ik? Zie de [README](https://github.com/GemeenteNijmegen/design-system?tab=readme-ov-file#configuring-the-github-repository) voor inrichting repo (alles is gedaan, maar de token in bovenste stap zal opnieuw gegenereerd moeten vermoed ik).

**Comment by joostvanderborg** [comment]
De branch protection override rol kan niet aangemaakt (enterprise only), maar ik heb een token weten te genereren die lijkt te werken. Eerste versie: https://www.npmjs.com/package/@gemeentenijmegen/design-tokens
