### ISSUE TITLE
'importing a module script failed' error in storybook

### ISSUE THREAD

**Issue by joostvanderborg** [GemeenteNijmegen/design-system#66]
Na merge van laatste PR geef GH pages een fout bij elke subpagina: https://gemeentenijmegen.github.io/design-system/?path=/docs/introduction-introductie--docs

**Comment by Michel-Verhoeven** [comment]
@joostvanderborg [Bypass voor Jykill](https://github.blog/news-insights/bypassing-jekyll-on-github-pages/) gecommit in de gh pages branche omdat Storybook gebruik maakt van files die starten met een underscore, de commit heeft het probleem opgelost
